// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWt1PQ5DkZyUiYdflP7NCgrKzoZrARPM',
    appId: '1:576217379328:android:d45cbc3a37c50839465ee5',
    messagingSenderId: '576217379328',
    projectId: 'app-check-cuoi',
    storageBucket: 'app-check-cuoi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApskmVQ3nBeb4CdiPcb20IowPIyKI5bw0',
    appId: '1:576217379328:ios:af021e6469fbf282465ee5',
    messagingSenderId: '576217379328',
    projectId: 'app-check-cuoi',
    storageBucket: 'app-check-cuoi.appspot.com',
    iosBundleId: 'com.example.appCheckIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApskmVQ3nBeb4CdiPcb20IowPIyKI5bw0',
    appId: '1:576217379328:ios:22aee7410f01fa1e465ee5',
    messagingSenderId: '576217379328',
    projectId: 'app-check-cuoi',
    storageBucket: 'app-check-cuoi.appspot.com',
    iosBundleId: 'com.example.appCheckIn.RunnerTests',
  );
}
